/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gpx.splitter

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.fail

class AppTest {
    @Test fun appHasAGreeting() {
        fail("haha")
    }
}
